// Curated name pools. Single broad American pool for Phase 1.
// Per-region/regional flavor pools land in Phase 6 alongside scouting reports.

export const FIRST_NAMES: readonly string[] = [
  'Abel','Adrian','Aiden','Alex','Andre','Angel','Anthony','Arturo','Asher','August',
  'Beau','Ben','Blake','Boone','Brady','Brennan','Brock','Bruno','Bryce','Caleb',
  'Calvin','Cameron','Carlos','Carter','Chase','Clay','Cole','Connor','Cooper','Cyrus',
  'Damian','Dane','Daniel','Dante','Davis','Deacon','Diego','Dom','Drew','Dustin',
  'Eli','Elias','Elliot','Emilio','Emmett','Enzo','Esteban','Ethan','Evan','Ezra',
  'Felix','Finn','Ford','Frankie','Gabe','Gavin','George','Grady','Graham','Grant',
  'Griffin','Hank','Harlan','Harvey','Heath','Hector','Henry','Holden','Hudson','Hugo',
  'Ian','Isaac','Isaiah','Jace','Jack','Jackson','Jaden','Jaime','Jake','Jameson',
  'Jared','Jasper','Javier','Jaxon','Jayce','Jaylen','Jed','Jefferson','Jensen','Jericho',
  'Jett','Joaquin','Joel','John','Jonah','Jordan','Jose','Josh','Judah','Julian',
  'Kade','Kai','Kayden','Keegan','Kellan','Kenji','Kenny','Kieran','Knox','Kobe',
  'Kyle','Landon','Lars','Leo','Levi','Liam','Lincoln','Logan','Lorenzo','Luca',
  'Luis','Luke','Mac','Malachi','Marco','Mario','Mason','Mateo','Maverick','Max',
  'Micah','Miguel','Miles','Milo','Mitch','Nate','Niko','Nolan','Oliver','Omar',
  'Orlando','Oscar','Otis','Owen','Pablo','Parker','Pedro','Peyton','Phoenix','Quincy',
  'Rafael','Ramon','Rashad','Reid','Remy','Rene','Reuben','Rhett','Ricardo','Rio',
  'River','Rocco','Ronan','Ross','Rowan','Roy','Ruben','Rudy','Ryan','Sage',
  'Salvador','Sam','Santiago','Saul','Sawyer','Sergio','Seth','Shane','Silas','Solomon',
  'Spencer','Stetson','Sullivan','Tate','Theo','Tobias','Tomas','Travis','Trent','Trevor',
  'Tristan','Ty','Vance','Vicente','Wade','Walker','Wendell','Wesley','Wilder','Wyatt',
  'Xavier','Yusuf','Zane','Zeke',
];

export const LAST_NAMES: readonly string[] = [
  'Acosta','Adair','Alvarez','Anderson','Archer','Arroyo','Atwood','Avery','Ayala','Bain',
  'Baker','Banks','Barlow','Barrett','Bauer','Beaumont','Becker','Bell','Beltran','Bennett',
  'Bishop','Blackburn','Blake','Bonilla','Booker','Boone','Bowen','Bradford','Brennan','Briggs',
  'Brock','Brooks','Bryant','Burgess','Burke','Burns','Cabrera','Caldwell','Campos','Cardenas',
  'Carmichael','Carrera','Carter','Castro','Chambers','Chandler','Chase','Chavez','Cisneros','Clay',
  'Clayton','Cobb','Cole','Coleman','Collins','Conrad','Contreras','Cordero','Cortez','Cowan',
  'Crawford','Crockett','Cross','Cruz','Cuevas','Dalton','Daniels','Dawson','Decker','Delgado',
  'Dempsey','Diaz','Dixon','Donovan','Doyle','Drake','Duncan','Durham','Eastman','Echeverria',
  'Eldridge','Ellis','Escobar','Esparza','Espinoza','Estrada','Everett','Faulkner','Ferguson','Fernandez',
  'Fielder','Finch','Finley','Fisher','Fitzgerald','Flores','Flynn','Ford','Fowler','Franco',
  'Fuentes','Gaines','Galvan','Garrett','Garrison','Garza','Gentry','Gibson','Gilmore','Glover',
  'Gomez','Gonzales','Granger','Graves','Greer','Griffin','Guerra','Guerrero','Guzman','Hadley',
  'Hale','Hamilton','Hammond','Harlow','Harper','Harrelson','Hawthorne','Hayes','Henderson','Hendricks',
  'Hernandez','Herrera','Hicks','Higgins','Hobbs','Holden','Hollister','Holloway','Hopkins','Horton',
  'Howell','Hudson','Hunt','Hurst','Ibarra','Ingram','Iverson','Jacobs','James','Jenkins',
  'Jensen','Jett','Jimenez','Joaquin','Jones','Joyner','Keenan','Keller','Kennedy','Kim',
  'Knox','Kowalski','Lambert','Landry','Langley','Larkin','Larsen','Lawson','Ledezma','Lemus',
  'Leon','Levine','Lewis','Lockhart','Logan','Long','Lopez','Lozano','Luna','Mack',
  'Magana','Maddox','Maldonado','Mallory','Marin','Marquez','Marshall','Martin','Martinez','Mason',
  'Massey','Mayer','McBride','McCabe','McCallister','McCoy','McGrath','McKinnon','Medina','Mejia',
  'Meléndez','Mendez','Mercado','Mercer','Merrick','Meyers','Mireles','Molina','Monroe','Montague',
  'Montero','Montoya','Moody','Moore','Morales','Moreno','Morris','Mosley','Munoz','Murillo',
  'Nash','Navarro','Nelson','Newcomb','Newton','Nieto','Norton','O\'Brien','O\'Connor','Ochoa',
  'Olivares','Ortega','Ortiz','Osborne','Otero','Padilla','Page','Palmer','Parra','Patel',
  'Patton','Paulson','Pearson','Peña','Perales','Peralta','Perez','Phelan','Pickett','Pierce',
  'Pinto','Polk','Ponce','Porter','Powell','Prado','Pratt','Quinn','Quintana','Ramos',
  'Randolph','Rangel','Reed','Reyes','Reynolds','Rhodes','Riley','Rios','Rivas','Rivera',
  'Roach','Robles','Rocha','Rodriguez','Rojas','Roman','Romero','Rosario','Rowe','Ruiz',
  'Rush','Salas','Salazar','Sanchez','Sandoval','Santiago','Santos','Saucedo','Savage','Schultz',
  'Sears','Sepulveda','Serrano','Sharp','Shaw','Shepherd','Sierra','Silva','Sims','Sinclair',
  'Solano','Solis','Soto','Spencer','Stanton','Stark','Stevens','Stockton','Stone','Strickland',
  'Suarez','Sullivan','Sutton','Tanner','Tapia','Tate','Taylor','Terrell','Thatcher','Thompson',
  'Tobias','Torres','Trujillo','Tucker','Underwood','Valdez','Valencia','Vargas','Vasquez','Vega',
  'Velasquez','Villa','Villanueva','Wade','Walsh','Ward','Watts','Weaver','Webb','Weller',
  'West','Whalen','Whitfield','Wilder','Wilkins','Williams','Winters','Wolfe','Woods','Yates',
  'Young','Zamora','Zapata','Zavala',
];

// Hometown pool — not strictly regional yet, but flavored toward small/mid US cities,
// plus a sprinkling of Caribbean/Latin American baseball hotbeds for realism.
export const HOMETOWNS: readonly string[] = [
  'Akron, OH','Albany, NY','Albuquerque, NM','Allentown, PA','Amarillo, TX','Asheville, NC',
  'Aurora, CO','Austin, TX','Bakersfield, CA','Baton Rouge, LA','Beaumont, TX','Bend, OR',
  'Billings, MT','Birmingham, AL','Boise, ID','Boulder, CO','Bozeman, MT','Brownsville, TX',
  'Buffalo, NY','Bushwick, NY','Cedar Rapids, IA','Champaign, IL','Charleston, SC','Chattanooga, TN',
  'Cheyenne, WY','Chico, CA','Coeur d\'Alene, ID','Columbia, MO','Columbus, GA','Corpus Christi, TX',
  'Council Bluffs, IA','Davenport, IA','Daytona Beach, FL','Decatur, IL','Des Moines, IA','Dover, DE',
  'Duluth, MN','Durango, CO','El Paso, TX','Erie, PA','Eugene, OR','Evansville, IN',
  'Fairbanks, AK','Fargo, ND','Fayetteville, AR','Flagstaff, AZ','Flint, MI','Fort Smith, AR',
  'Fresno, CA','Gainesville, FL','Galveston, TX','Grand Forks, ND','Grand Junction, CO','Great Falls, MT',
  'Green Bay, WI','Greensboro, NC','Gulfport, MS','Harrisburg, PA','Hartford, CT','Helena, MT',
  'Hilo, HI','Huntsville, AL','Idaho Falls, ID','Iowa City, IA','Jackson, MS','Jacksonville, FL',
  'Joplin, MO','Juneau, AK','Kalamazoo, MI','Kalispell, MT','Kingsport, TN','Knoxville, TN',
  'La Crosse, WI','Laredo, TX','Las Cruces, NM','Lexington, KY','Lincoln, NE','Little Rock, AR',
  'Lubbock, TX','Macon, GA','Madison, WI','Manchester, NH','Mansfield, OH','Mesa, AZ',
  'Missoula, MT','Mobile, AL','Modesto, CA','Montgomery, AL','Montpelier, VT','Naperville, IL',
  'Nashua, NH','New Haven, CT','New London, CT','Norfolk, VA','Ogden, UT','Olathe, KS',
  'Olympia, WA','Omaha, NE','Pasadena, CA','Pawtucket, RI','Pensacola, FL','Pierre, SD',
  'Pocatello, ID','Portland, ME','Providence, RI','Pueblo, CO','Quincy, MA','Raleigh, NC',
  'Rapid City, SD','Reno, NV','Richmond, VA','Roanoke, VA','Rochester, MN','Roseburg, OR',
  'Salem, OR','Salinas, CA','San Antonio, TX','San Luis Obispo, CA','Santa Fe, NM','Savannah, GA',
  'Scranton, PA','Sheboygan, WI','Shreveport, LA','Sioux Falls, SD','South Bend, IN','Spokane, WA',
  'Springfield, IL','Springfield, MO','Stockton, CA','Syracuse, NY','Tallahassee, FL','Toledo, OH',
  'Topeka, KS','Tulsa, OK','Tupelo, MS','Tuscaloosa, AL','Tyler, TX','Utica, NY',
  'Waco, TX','Walla Walla, WA','Wenatchee, WA','Wichita, KS','Wilmington, DE','Yakima, WA',
  // Latin American baseball hotbeds — common in MLB and worth representing.
  'San Pedro de Macorís, DR','Santo Domingo, DR','La Romana, DR','Caracas, VZ','Maracay, VZ',
  'Valencia, VZ','Havana, CU','Holguín, CU','Mayagüez, PR','Carolina, PR','San Juan, PR',
  'Culiacán, MX','Hermosillo, MX','Ciudad Obregón, MX','Tokyo, JP','Osaka, JP',
  'Seoul, KR','Taipei, TW',
];
