import type { Team, Stadium, TeamId, StadiumId, Conference, Division } from '../world/types.js';

// Static identity data for the founding 16. Phase 0 keeps this hand-curated;
// later phases may seed-derive flavor variants but team identities stay fixed.

interface TeamSeed {
  readonly id: TeamId;
  readonly city: string;
  readonly nickname: string;
  readonly abbr: string;
  readonly conference: Conference;
  readonly division: Division;
  readonly colors: { primary: string; secondary: string; accent: string };
  readonly mascot: string;
  readonly stadium: {
    readonly id: StadiumId;
    readonly name: string;
    readonly leftFt: number;
    readonly leftCenterFt: number;
    readonly centerFt: number;
    readonly rightCenterFt: number;
    readonly rightFt: number;
    readonly wallHeightFt: number;
    readonly foulTerritoryRating: number;
    readonly moundHeightIn: number;
    readonly grassPattern: 'plain' | 'checkerboard' | 'radial' | 'ringed' | 'striped';
    readonly grassShade: string;
    readonly seatPalette: readonly string[];
    readonly dayGameBias: number;
    readonly crowdDensityCurve: 'home-heavy' | 'flat' | 'late-arrivers';
    readonly quirk: Stadium['quirk'];
  };
}

export const TEAM_SEEDS: readonly TeamSeed[] = [
  // Western — Pacific
  {
    id: 'anc',
    city: 'Anchorage',
    nickname: 'Halibut',
    abbr: 'ANC',
    conference: 'West',
    division: 'Pacific',
    colors: { primary: '#0d2b4f', secondary: '#c8d3dc', accent: '#e08a3a' },
    mascot: 'Hal the Halibut',
    stadium: {
      id: 'anc-tide',
      name: 'Tide Park',
      leftFt: 335, leftCenterFt: 372, centerFt: 415, rightCenterFt: 360, rightFt: 308,
      wallHeightFt: 9,
      foulTerritoryRating: 6,
      moundHeightIn: 10,
      grassPattern: 'ringed',
      grassShade: '#3b6e3a',
      seatPalette: ['#0d2b4f', '#c8d3dc', '#1d3a5f'],
      dayGameBias: 0.7,
      crowdDensityCurve: 'flat',
      quirk: { kind: 'short-porch', side: 'right', distanceFt: 308 },
    },
  },
  {
    id: 'hnl',
    city: 'Honolulu',
    nickname: 'Outriggers',
    abbr: 'HNL',
    conference: 'West',
    division: 'Pacific',
    colors: { primary: '#0a8a8c', secondary: '#f3d7a3', accent: '#ef6f5c' },
    mascot: 'Kai the Outrigger',
    stadium: {
      id: 'hnl-diamond',
      name: 'Diamond Head Diamond',
      leftFt: 320, leftCenterFt: 376, centerFt: 405, rightCenterFt: 376, rightFt: 320,
      wallHeightFt: 12,
      foulTerritoryRating: 4,
      moundHeightIn: 10,
      grassPattern: 'checkerboard',
      grassShade: '#4f8e5b',
      seatPalette: ['#0a8a8c', '#f3d7a3', '#ef6f5c'],
      dayGameBias: 0.55,
      crowdDensityCurve: 'late-arrivers',
      quirk: { kind: 'wind-tunnel', direction: 'cross' },
    },
  },
  {
    id: 'spk',
    city: 'Spokane',
    nickname: 'Lumberjacks',
    abbr: 'SPK',
    conference: 'West',
    division: 'Pacific',
    colors: { primary: '#244e2b', secondary: '#f3eedb', accent: '#a93226' },
    mascot: 'Big Tim',
    stadium: {
      id: 'spk-pinegrove',
      name: 'Pinegrove Field',
      leftFt: 340, leftCenterFt: 380, centerFt: 410, rightCenterFt: 380, rightFt: 340,
      wallHeightFt: 14,
      foulTerritoryRating: 5,
      moundHeightIn: 10,
      grassPattern: 'striped',
      grassShade: '#365e3a',
      seatPalette: ['#244e2b', '#f3eedb', '#7a4a2c'],
      dayGameBias: 0.45,
      crowdDensityCurve: 'home-heavy',
      quirk: { kind: 'ivy-wall', side: 'left' },
    },
  },
  {
    id: 'boi',
    city: 'Boise',
    nickname: 'Steelheads',
    abbr: 'BOI',
    conference: 'West',
    division: 'Pacific',
    colors: { primary: '#3c4a55', secondary: '#6391b3', accent: '#b87333' },
    mascot: 'Rivet',
    stadium: {
      id: 'boi-river',
      name: 'River Reach',
      leftFt: 332, leftCenterFt: 370, centerFt: 408, rightCenterFt: 365, rightFt: 332,
      wallHeightFt: 11,
      foulTerritoryRating: 5,
      moundHeightIn: 10,
      grassPattern: 'plain',
      grassShade: '#3a6e44',
      seatPalette: ['#3c4a55', '#6391b3', '#b87333'],
      dayGameBias: 0.5,
      crowdDensityCurve: 'flat',
      quirk: { kind: 'clock-tower-in-play' },
    },
  },

  // Western — Mountain
  {
    id: 'tus',
    city: 'Tucson',
    nickname: 'Saguaros',
    abbr: 'TUS',
    conference: 'West',
    division: 'Mountain',
    colors: { primary: '#3e6b3e', secondary: '#d8b97a', accent: '#e26a2c' },
    mascot: 'Saguaro Sam',
    stadium: {
      id: 'tus-saguaro',
      name: 'Saguaro Park',
      leftFt: 345, leftCenterFt: 385, centerFt: 410, rightCenterFt: 385, rightFt: 345,
      wallHeightFt: 8,
      foulTerritoryRating: 8,
      moundHeightIn: 10,
      grassPattern: 'plain',
      grassShade: '#5a7a3e',
      seatPalette: ['#3e6b3e', '#d8b97a', '#e26a2c'],
      dayGameBias: 0.35,
      crowdDensityCurve: 'late-arrivers',
      quirk: { kind: 'mascot-statue', side: 'center' },
    },
  },
  {
    id: 'che',
    city: 'Cheyenne',
    nickname: 'Stampede',
    abbr: 'CHE',
    conference: 'West',
    division: 'Mountain',
    colors: { primary: '#8a3b1e', secondary: '#f0e8d0', accent: '#1c1c1c' },
    mascot: 'Buck',
    stadium: {
      id: 'che-frontier',
      name: 'Frontier Field',
      leftFt: 330, leftCenterFt: 365, centerFt: 400, rightCenterFt: 365, rightFt: 330,
      wallHeightFt: 9,
      foulTerritoryRating: 6,
      moundHeightIn: 10,
      grassPattern: 'plain',
      grassShade: '#6a7a3a',
      seatPalette: ['#8a3b1e', '#f0e8d0', '#1c1c1c'],
      dayGameBias: 0.5,
      crowdDensityCurve: 'flat',
      quirk: { kind: 'wind-tunnel', direction: 'out' },
    },
  },
  {
    id: 'bdr',
    city: 'Boulder',
    nickname: 'Flatirons',
    abbr: 'BDR',
    conference: 'West',
    division: 'Mountain',
    colors: { primary: '#5a5d63', secondary: '#7fb6e5', accent: '#e8c545' },
    mascot: 'Slabby',
    stadium: {
      id: 'bdr-granite',
      name: 'Granite Glen',
      leftFt: 348, leftCenterFt: 395, centerFt: 420, rightCenterFt: 390, rightFt: 348,
      wallHeightFt: 10,
      foulTerritoryRating: 7,
      moundHeightIn: 10,
      grassPattern: 'radial',
      grassShade: '#4a7a44',
      seatPalette: ['#5a5d63', '#7fb6e5', '#e8c545'],
      dayGameBias: 0.55,
      crowdDensityCurve: 'home-heavy',
      quirk: { kind: 'altitude-thin-air', elevationFt: 5430 },
    },
  },
  {
    id: 'sfe',
    city: 'Santa Fe',
    nickname: 'Vaqueros',
    abbr: 'SFE',
    conference: 'West',
    division: 'Mountain',
    colors: { primary: '#b35a31', secondary: '#3aa6a2', accent: '#f0e2c8' },
    mascot: 'Don Diego',
    stadium: {
      id: 'sfe-adobe',
      name: 'Adobe Yard',
      leftFt: 308, leftCenterFt: 372, centerFt: 405, rightCenterFt: 380, rightFt: 340,
      wallHeightFt: 16,
      foulTerritoryRating: 5,
      moundHeightIn: 10,
      grassPattern: 'striped',
      grassShade: '#6a8a3e',
      seatPalette: ['#b35a31', '#3aa6a2', '#f0e2c8'],
      dayGameBias: 0.45,
      crowdDensityCurve: 'flat',
      quirk: { kind: 'short-porch', side: 'left', distanceFt: 308 },
    },
  },

  // Eastern — Heartland
  {
    id: 'wic',
    city: 'Wichita',
    nickname: 'Jetstream',
    abbr: 'WIC',
    conference: 'East',
    division: 'Heartland',
    colors: { primary: '#3e4a55', secondary: '#3aa6e0', accent: '#f4f4f4' },
    mascot: 'Mach',
    stadium: {
      id: 'wic-skystream',
      name: 'Skystream Park',
      leftFt: 325, leftCenterFt: 370, centerFt: 400, rightCenterFt: 365, rightFt: 325,
      wallHeightFt: 8,
      foulTerritoryRating: 4,
      moundHeightIn: 10,
      grassPattern: 'striped',
      grassShade: '#4a7a44',
      seatPalette: ['#3e4a55', '#3aa6e0', '#f4f4f4'],
      dayGameBias: 0.5,
      crowdDensityCurve: 'late-arrivers',
      quirk: { kind: 'wind-tunnel', direction: 'out' },
    },
  },
  {
    id: 'dsm',
    city: 'Des Moines',
    nickname: 'Drovers',
    abbr: 'DSM',
    conference: 'East',
    division: 'Heartland',
    colors: { primary: '#9b2a1c', secondary: '#e6d5a6', accent: '#5a3a22' },
    mascot: 'Hoss',
    stadium: {
      id: 'dsm-cattle',
      name: 'Cattleyard Park',
      leftFt: 338, leftCenterFt: 378, centerFt: 408, rightCenterFt: 378, rightFt: 338,
      wallHeightFt: 10,
      foulTerritoryRating: 7,
      moundHeightIn: 10,
      grassPattern: 'plain',
      grassShade: '#446e3a',
      seatPalette: ['#9b2a1c', '#e6d5a6', '#5a3a22'],
      dayGameBias: 0.5,
      crowdDensityCurve: 'home-heavy',
      quirk: { kind: 'pond-beyond-rf' },
    },
  },
  {
    id: 'mad',
    city: 'Madison',
    nickname: 'Glaciers',
    abbr: 'MAD',
    conference: 'East',
    division: 'Heartland',
    colors: { primary: '#a9d3e6', secondary: '#ffffff', accent: '#1f2d4a' },
    mascot: 'Drift',
    stadium: {
      id: 'mad-glacier',
      name: 'Glacier Hollow',
      leftFt: 342, leftCenterFt: 390, centerFt: 425, rightCenterFt: 390, rightFt: 342,
      wallHeightFt: 12,
      foulTerritoryRating: 6,
      moundHeightIn: 10,
      grassPattern: 'ringed',
      grassShade: '#3e6e44',
      seatPalette: ['#a9d3e6', '#ffffff', '#1f2d4a'],
      dayGameBias: 0.5,
      crowdDensityCurve: 'flat',
      quirk: { kind: 'deep-center', distanceFt: 425 },
    },
  },
  {
    id: 'lub',
    city: 'Lubbock',
    nickname: 'Cyclones',
    abbr: 'LUB',
    conference: 'East',
    division: 'Heartland',
    colors: { primary: '#a89682', secondary: '#3a3a3a', accent: '#f1c40f' },
    mascot: 'Whirly',
    stadium: {
      id: 'lub-twister',
      name: 'Twister Bowl',
      leftFt: 330, leftCenterFt: 372, centerFt: 405, rightCenterFt: 372, rightFt: 330,
      wallHeightFt: 9,
      foulTerritoryRating: 3,
      moundHeightIn: 10,
      grassPattern: 'plain',
      grassShade: '#5a6e3a',
      seatPalette: ['#a89682', '#3a3a3a', '#f1c40f'],
      dayGameBias: 0.4,
      crowdDensityCurve: 'late-arrivers',
      quirk: { kind: 'wind-tunnel', direction: 'cross' },
    },
  },

  // Eastern — Atlantic
  {
    id: 'lou',
    city: 'Louisville',
    nickname: 'Spiders',
    abbr: 'LOU',
    conference: 'East',
    division: 'Atlantic',
    colors: { primary: '#1c1c1c', secondary: '#d4af37', accent: '#f0e6c8' },
    mascot: 'Webfoot',
    stadium: {
      id: 'lou-webwork',
      name: 'Webwork Park',
      leftFt: 333, leftCenterFt: 376, centerFt: 405, rightCenterFt: 376, rightFt: 325,
      wallHeightFt: 11,
      foulTerritoryRating: 5,
      moundHeightIn: 10,
      grassPattern: 'checkerboard',
      grassShade: '#3a6e44',
      seatPalette: ['#1c1c1c', '#d4af37', '#f0e6c8'],
      dayGameBias: 0.5,
      crowdDensityCurve: 'home-heavy',
      quirk: { kind: 'ivy-wall', side: 'left' },
    },
  },
  {
    id: 'btv',
    city: 'Burlington',
    nickname: 'Maple Kings',
    abbr: 'BTV',
    conference: 'East',
    division: 'Atlantic',
    colors: { primary: '#a93226', secondary: '#1d4a2f', accent: '#f0e6c8' },
    mascot: 'King Maple',
    stadium: {
      id: 'btv-sapwood',
      name: 'Sapwood Stadium',
      leftFt: 312, leftCenterFt: 368, centerFt: 402, rightCenterFt: 372, rightFt: 338,
      wallHeightFt: 18,
      foulTerritoryRating: 5,
      moundHeightIn: 10,
      grassPattern: 'striped',
      grassShade: '#3a6e3e',
      seatPalette: ['#a93226', '#1d4a2f', '#f0e6c8'],
      dayGameBias: 0.5,
      crowdDensityCurve: 'home-heavy',
      quirk: { kind: 'mascot-statue', side: 'left' },
    },
  },
  {
    id: 'avl',
    city: 'Asheville',
    nickname: 'Switchbacks',
    abbr: 'AVL',
    conference: 'East',
    division: 'Atlantic',
    colors: { primary: '#5a7d8c', secondary: '#7a8f5a', accent: '#d4a14a' },
    mascot: 'Switchback Sal',
    stadium: {
      id: 'avl-hollow',
      name: 'Switchback Hollow',
      leftFt: 336, leftCenterFt: 380, centerFt: 412, rightCenterFt: 380, rightFt: 336,
      wallHeightFt: 10,
      foulTerritoryRating: 5,
      moundHeightIn: 10,
      grassPattern: 'radial',
      grassShade: '#3e6e44',
      seatPalette: ['#5a7d8c', '#7a8f5a', '#d4a14a'],
      dayGameBias: 0.5,
      crowdDensityCurve: 'flat',
      quirk: { kind: 'hill-cf' },
    },
  },
  {
    id: 'pwm',
    city: 'Portland',
    nickname: 'Lighthouses',
    abbr: 'PWM',
    conference: 'East',
    division: 'Atlantic',
    colors: { primary: '#1f2d4a', secondary: '#a3aab2', accent: '#f1c40f' },
    mascot: 'Beacon',
    stadium: {
      id: 'pwm-beacon',
      name: 'Beacon Field',
      leftFt: 330, leftCenterFt: 372, centerFt: 400, rightCenterFt: 360, rightFt: 305,
      wallHeightFt: 22,
      foulTerritoryRating: 4,
      moundHeightIn: 10,
      grassPattern: 'striped',
      grassShade: '#365e3a',
      seatPalette: ['#1f2d4a', '#a3aab2', '#f1c40f'],
      dayGameBias: 0.5,
      crowdDensityCurve: 'home-heavy',
      quirk: { kind: 'mascot-statue', side: 'right' },
    },
  },
] as const;

// Convert seeds into the canonical Team and Stadium shapes.
export const buildTeamsAndStadiums = (): { teams: Team[]; stadiums: Stadium[] } => {
  const teams: Team[] = TEAM_SEEDS.map((seed) => ({
    id: seed.id,
    city: seed.city,
    nickname: seed.nickname,
    abbr: seed.abbr,
    conference: seed.conference,
    division: seed.division,
    colors: seed.colors,
    mascot: seed.mascot,
    stadiumId: seed.stadium.id,
  }));

  const stadiums: Stadium[] = TEAM_SEEDS.map((seed) => ({
    id: seed.stadium.id,
    name: seed.stadium.name,
    teamId: seed.id,
    dimensions: {
      leftFt: seed.stadium.leftFt,
      leftCenterFt: seed.stadium.leftCenterFt,
      centerFt: seed.stadium.centerFt,
      rightCenterFt: seed.stadium.rightCenterFt,
      rightFt: seed.stadium.rightFt,
      wallHeightFt: seed.stadium.wallHeightFt,
      foulTerritoryRating: seed.stadium.foulTerritoryRating,
      moundHeightIn: seed.stadium.moundHeightIn,
    },
    quirk: seed.stadium.quirk,
    atmosphere: {
      grassPattern: seed.stadium.grassPattern,
      grassShade: seed.stadium.grassShade,
      seatPalette: seed.stadium.seatPalette,
      dayGameBias: seed.stadium.dayGameBias,
      crowdDensityCurve: seed.stadium.crowdDensityCurve,
    },
  }));

  return { teams, stadiums };
};
